// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block_meta.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockRequestType int32

const (
	BlockRequestType_default_type  BlockRequestType = 0
	BlockRequestType_only_header   BlockRequestType = 1
	BlockRequestType_whole_content BlockRequestType = 2
)

var BlockRequestType_name = map[int32]string{
	0: "default_type",
	1: "only_header",
	2: "whole_content",
}

var BlockRequestType_value = map[string]int32{
	"default_type":  0,
	"only_header":   1,
	"whole_content": 2,
}

func (x BlockRequestType) String() string {
	return proto.EnumName(BlockRequestType_name, int32(x))
}

func (BlockRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ce63c24a9154ceb, []int{0}
}

type BroadcastMsgType int32

const (
	BroadcastMsgType_unknown_msg BroadcastMsgType = 0
	// 共识相关
	BroadcastMsgType_send_pbft_msg   BroadcastMsgType = 1
	BroadcastMsgType_send_block_meta BroadcastMsgType = 2
	// tx
	BroadcastMsgType_send_tx BroadcastMsgType = 10
	// blockchain
	BroadcastMsgType_request_load_block BroadcastMsgType = 20
)

var BroadcastMsgType_name = map[int32]string{
	0:  "unknown_msg",
	1:  "send_pbft_msg",
	2:  "send_block_meta",
	10: "send_tx",
	20: "request_load_block",
}

var BroadcastMsgType_value = map[string]int32{
	"unknown_msg":        0,
	"send_pbft_msg":      1,
	"send_block_meta":    2,
	"send_tx":            10,
	"request_load_block": 20,
}

func (x BroadcastMsgType) String() string {
	return proto.EnumName(BroadcastMsgType_name, int32(x))
}

func (BroadcastMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ce63c24a9154ceb, []int{1}
}

type BlockMeta struct {
	BlockHeight          uint64      `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	CurVerfier           *Verifier   `protobuf:"bytes,2,opt,name=cur_verfier,json=curVerfier,proto3" json:"cur_verfier,omitempty"`
	VerifierNo           uint32      `protobuf:"varint,3,opt,name=verifier_no,json=verifierNo,proto3" json:"verifier_no,omitempty"`
	Verifiers            []*Verifier `protobuf:"bytes,4,rep,name=verifiers,proto3" json:"verifiers,omitempty"`
	LastView             uint64      `protobuf:"varint,5,opt,name=last_view,json=lastView,proto3" json:"last_view,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BlockMeta) Reset()         { *m = BlockMeta{} }
func (m *BlockMeta) String() string { return proto.CompactTextString(m) }
func (*BlockMeta) ProtoMessage()    {}
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63c24a9154ceb, []int{0}
}

func (m *BlockMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMeta.Unmarshal(m, b)
}
func (m *BlockMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMeta.Marshal(b, m, deterministic)
}
func (m *BlockMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMeta.Merge(m, src)
}
func (m *BlockMeta) XXX_Size() int {
	return xxx_messageInfo_BlockMeta.Size(m)
}
func (m *BlockMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMeta.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMeta proto.InternalMessageInfo

func (m *BlockMeta) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BlockMeta) GetCurVerfier() *Verifier {
	if m != nil {
		return m.CurVerfier
	}
	return nil
}

func (m *BlockMeta) GetVerifierNo() uint32 {
	if m != nil {
		return m.VerifierNo
	}
	return 0
}

func (m *BlockMeta) GetVerifiers() []*Verifier {
	if m != nil {
		return m.Verifiers
	}
	return nil
}

func (m *BlockMeta) GetLastView() uint64 {
	if m != nil {
		return m.LastView
	}
	return 0
}

type BlockRequest struct {
	BlockNum             int64            `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	RequestType          BlockRequestType `protobuf:"varint,2,opt,name=request_type,json=requestType,proto3,enum=BlockRequestType" json:"request_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63c24a9154ceb, []int{1}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetBlockNum() int64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *BlockRequest) GetRequestType() BlockRequestType {
	if m != nil {
		return m.RequestType
	}
	return BlockRequestType_default_type
}

type BlockResponse struct {
	RequestType          BlockRequestType `protobuf:"varint,2,opt,name=request_type,json=requestType,proto3,enum=BlockRequestType" json:"request_type,omitempty"`
	Block                *PbftBlock       `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63c24a9154ceb, []int{2}
}

func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetRequestType() BlockRequestType {
	if m != nil {
		return m.RequestType
	}
	return BlockRequestType_default_type
}

func (m *BlockResponse) GetBlock() *PbftBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterEnum("BlockRequestType", BlockRequestType_name, BlockRequestType_value)
	proto.RegisterEnum("BroadcastMsgType", BroadcastMsgType_name, BroadcastMsgType_value)
	proto.RegisterType((*BlockMeta)(nil), "BlockMeta")
	proto.RegisterType((*BlockRequest)(nil), "BlockRequest")
	proto.RegisterType((*BlockResponse)(nil), "BlockResponse")
}

func init() { proto.RegisterFile("block_meta.proto", fileDescriptor_7ce63c24a9154ceb) }

var fileDescriptor_7ce63c24a9154ceb = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xd7, 0xed, 0x16, 0xb6, 0xe3, 0x96, 0x7a, 0x0d, 0x42, 0x11, 0x1c, 0x08, 0xbd, 0x50,
	0xf5, 0xd0, 0x43, 0xe1, 0x09, 0x7a, 0xda, 0xcb, 0xae, 0x56, 0x11, 0xda, 0x03, 0x17, 0xcb, 0x4d,
	0xa6, 0x6d, 0xb4, 0x89, 0x1d, 0xfc, 0xa7, 0xa1, 0x8f, 0xc7, 0x9b, 0xa1, 0xd8, 0x8d, 0x0a, 0x1c,
	0xf7, 0x16, 0xff, 0xe6, 0x9b, 0x2f, 0xf3, 0x8d, 0x06, 0xd8, 0xb6, 0xd2, 0xf9, 0xb3, 0xa8, 0xd1,
	0xc9, 0x55, 0x63, 0xb4, 0xd3, 0x1f, 0x66, 0xb9, 0x56, 0x16, 0x95, 0xf5, 0x36, 0x82, 0xf9, 0x6f,
	0x02, 0xe3, 0x4d, 0xa7, 0xba, 0x47, 0x27, 0xf9, 0x67, 0x98, 0xc4, 0x96, 0x03, 0x96, 0xfb, 0x83,
	0x4b, 0x48, 0x4a, 0x16, 0xd7, 0x19, 0x0d, 0xec, 0x2e, 0x20, 0xbe, 0x04, 0x9a, 0x7b, 0x23, 0x8e,
	0x68, 0x76, 0x25, 0x9a, 0x64, 0x90, 0x92, 0x05, 0x5d, 0x8f, 0x57, 0x47, 0x34, 0x65, 0x07, 0x32,
	0xc8, 0xbd, 0x79, 0x8a, 0x45, 0xfe, 0x09, 0x68, 0xcf, 0x85, 0xd2, 0xc9, 0x30, 0x25, 0x8b, 0x69,
	0x06, 0x3d, 0x7a, 0xd0, 0xfc, 0x0b, 0x8c, 0xfb, 0x97, 0x4d, 0xae, 0xd3, 0xe1, 0xbf, 0x56, 0x97,
	0x1a, 0xff, 0x08, 0xe3, 0x4a, 0x5a, 0x27, 0x8e, 0x25, 0xb6, 0xc9, 0x28, 0x4c, 0x75, 0xd3, 0x81,
	0xa7, 0x12, 0xdb, 0xb9, 0x84, 0x49, 0x88, 0x90, 0xe1, 0x4f, 0x8f, 0xd6, 0x75, 0xe2, 0x98, 0x42,
	0xf9, 0x3a, 0x44, 0x18, 0x66, 0x37, 0x01, 0x3c, 0xf8, 0x9a, 0x7f, 0x83, 0x89, 0x89, 0x3a, 0xe1,
	0x4e, 0x0d, 0x86, 0x00, 0x6f, 0xd6, 0xb7, 0xab, 0xbf, 0x1d, 0xbe, 0x9f, 0x1a, 0xcc, 0xa8, 0xb9,
	0x3c, 0xe6, 0x7b, 0x98, 0x9e, 0x05, 0xb6, 0xe9, 0x36, 0xf8, 0x32, 0x1b, 0x9e, 0xc2, 0x28, 0x0c,
	0x12, 0x56, 0x41, 0xd7, 0xb0, 0x7a, 0xdc, 0xee, 0x5c, 0x6c, 0x89, 0x85, 0xe5, 0x1d, 0xb0, 0xff,
	0x2d, 0x38, 0x83, 0x49, 0x81, 0x3b, 0xe9, 0xab, 0xf8, 0x2f, 0x76, 0xc5, 0x67, 0x40, 0xb5, 0xaa,
	0x4e, 0xe2, 0x80, 0xb2, 0x40, 0xc3, 0x08, 0xbf, 0x85, 0x69, 0x7b, 0xd0, 0x15, 0x8a, 0x5c, 0x2b,
	0x87, 0xca, 0xb1, 0xc1, 0xb2, 0x01, 0xb6, 0x31, 0x5a, 0x16, 0xb9, 0xb4, 0xee, 0xde, 0xee, 0x83,
	0xd3, 0x0c, 0xa8, 0x57, 0xcf, 0x4a, 0xb7, 0x4a, 0xd4, 0x76, 0xcf, 0xae, 0xba, 0x3e, 0x8b, 0xaa,
	0x10, 0xcd, 0x76, 0xe7, 0x02, 0x22, 0xfc, 0x2d, 0xcc, 0x02, 0xba, 0xdc, 0x0e, 0x1b, 0x70, 0x0a,
	0xaf, 0x03, 0x74, 0xbf, 0x18, 0xf0, 0xf7, 0xc0, 0xfb, 0xec, 0x95, 0x96, 0x67, 0x25, 0x7b, 0xb7,
	0x61, 0x30, 0xaa, 0x75, 0x81, 0xd5, 0x23, 0xf9, 0x11, 0x3f, 0xb6, 0xaf, 0xc2, 0x91, 0x7d, 0xfd,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x76, 0x76, 0x5f, 0x89, 0x02, 0x00, 0x00,
}
