// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block_meta.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockMeta struct {
	BlockHeight          uint64      `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	CurVerfier           *Verifier   `protobuf:"bytes,2,opt,name=cur_verfier,json=curVerfier,proto3" json:"cur_verfier,omitempty"`
	VerifierNo           uint32      `protobuf:"varint,3,opt,name=verifier_no,json=verifierNo,proto3" json:"verifier_no,omitempty"`
	Verifiers            []*Verifier `protobuf:"bytes,4,rep,name=verifiers,proto3" json:"verifiers,omitempty"`
	LastView             uint64      `protobuf:"varint,5,opt,name=last_view,json=lastView,proto3" json:"last_view,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BlockMeta) Reset()         { *m = BlockMeta{} }
func (m *BlockMeta) String() string { return proto.CompactTextString(m) }
func (*BlockMeta) ProtoMessage()    {}
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce63c24a9154ceb, []int{0}
}

func (m *BlockMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMeta.Unmarshal(m, b)
}
func (m *BlockMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMeta.Marshal(b, m, deterministic)
}
func (m *BlockMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMeta.Merge(m, src)
}
func (m *BlockMeta) XXX_Size() int {
	return xxx_messageInfo_BlockMeta.Size(m)
}
func (m *BlockMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMeta.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMeta proto.InternalMessageInfo

func (m *BlockMeta) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BlockMeta) GetCurVerfier() *Verifier {
	if m != nil {
		return m.CurVerfier
	}
	return nil
}

func (m *BlockMeta) GetVerifierNo() uint32 {
	if m != nil {
		return m.VerifierNo
	}
	return 0
}

func (m *BlockMeta) GetVerifiers() []*Verifier {
	if m != nil {
		return m.Verifiers
	}
	return nil
}

func (m *BlockMeta) GetLastView() uint64 {
	if m != nil {
		return m.LastView
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockMeta)(nil), "BlockMeta")
}

func init() { proto.RegisterFile("block_meta.proto", fileDescriptor_7ce63c24a9154ceb) }

var fileDescriptor_7ce63c24a9154ceb = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xca, 0xc9, 0x4f,
	0xce, 0x8e, 0xcf, 0x4d, 0x2d, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x4f, 0xce,
	0xcf, 0x2b, 0x4e, 0xcd, 0x2b, 0x2e, 0x2d, 0x86, 0x08, 0x28, 0x1d, 0x64, 0xe4, 0xe2, 0x74, 0x02,
	0xa9, 0xf2, 0x4d, 0x2d, 0x49, 0x14, 0x52, 0xe4, 0xe2, 0x81, 0x68, 0xc9, 0x48, 0xcd, 0x4c, 0xcf,
	0x28, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0xe2, 0x06, 0x8b, 0x79, 0x80, 0x85, 0x84, 0xb4,
	0xb8, 0xb8, 0x93, 0x4b, 0x8b, 0xe2, 0xcb, 0x52, 0x8b, 0xd2, 0x32, 0x53, 0x8b, 0x24, 0x98, 0x14,
	0x18, 0x35, 0xb8, 0x8d, 0x38, 0xf5, 0xca, 0x52, 0x8b, 0x32, 0x41, 0x02, 0x41, 0x5c, 0xc9, 0xa5,
	0x45, 0x61, 0x10, 0x49, 0x21, 0x79, 0x2e, 0x6e, 0x98, 0x78, 0x7c, 0x5e, 0xbe, 0x04, 0xb3, 0x02,
	0xa3, 0x06, 0x6f, 0x10, 0x17, 0x4c, 0xc8, 0x2f, 0x5f, 0x48, 0x9d, 0x8b, 0x13, 0xc6, 0x2b, 0x96,
	0x60, 0x51, 0x60, 0x46, 0x35, 0x0a, 0x21, 0x27, 0x24, 0xcd, 0xc5, 0x99, 0x93, 0x58, 0x5c, 0x12,
	0x5f, 0x96, 0x99, 0x5a, 0x2e, 0xc1, 0x0a, 0x76, 0x15, 0x07, 0x48, 0x20, 0x2c, 0x33, 0xb5, 0xdc,
	0x49, 0x8a, 0x8b, 0x0b, 0xe1, 0xd1, 0x00, 0xc6, 0x28, 0x24, 0x5e, 0x12, 0x1b, 0xd8, 0x9b, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xdf, 0x80, 0x18, 0x0b, 0x01, 0x00, 0x00,
}
