// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Amount struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Amount) Reset()         { *m = Amount{} }
func (m *Amount) String() string { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()    {}
func (*Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *Amount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amount.Unmarshal(m, b)
}
func (m *Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amount.Marshal(b, m, deterministic)
}
func (m *Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amount.Merge(m, src)
}
func (m *Amount) XXX_Size() int {
	return xxx_messageInfo_Amount.Size(m)
}
func (m *Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_Amount proto.InternalMessageInfo

func (m *Amount) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type Tx struct {
	Sender               *Address `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Recipient            *Address `protobuf:"bytes,2,opt,name=Recipient,proto3" json:"Recipient,omitempty"`
	Amount               *Amount  `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Sequeue              string   `protobuf:"bytes,4,opt,name=sequeue,proto3" json:"sequeue,omitempty"`
	Input                []byte   `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Sign                 []byte   `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetSender() *Address {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Tx) GetRecipient() *Address {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *Tx) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Tx) GetSequeue() string {
	if m != nil {
		return m.Sequeue
	}
	return ""
}

func (m *Tx) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Tx) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "address")
	proto.RegisterType((*Amount)(nil), "amount")
	proto.RegisterType((*Tx)(nil), "tx")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xc9, 0xba, 0xcd, 0xba, 0xa3, 0x07, 0x1d, 0x44, 0x72, 0x33, 0x54, 0x90, 0x9e, 0x7a,
	0xd0, 0x37, 0xf0, 0x09, 0x24, 0xde, 0xbc, 0xc5, 0x66, 0x90, 0x80, 0x4d, 0x6a, 0xfe, 0x80, 0xef,
	0xe5, 0x0b, 0x8a, 0x49, 0x5a, 0x61, 0x6f, 0xbf, 0xdf, 0xcc, 0x47, 0xe6, 0x23, 0x70, 0x9d, 0x82,
	0x76, 0x51, 0x4f, 0xc9, 0x7a, 0x37, 0x2e, 0xc1, 0x27, 0xdf, 0xdf, 0xc3, 0x41, 0x1b, 0x13, 0x28,
	0x46, 0x14, 0x1b, 0x0a, 0x26, 0xd9, 0x70, 0x54, 0xab, 0xf6, 0x12, 0xb8, 0x9e, 0x7d, 0x76, 0x09,
	0x6f, 0x57, 0x6a, 0x91, 0x66, 0xfd, 0x0f, 0x83, 0x5d, 0xfa, 0x46, 0x09, 0xfc, 0x95, 0x9c, 0xa1,
	0x50, 0xd6, 0x17, 0x8f, 0xe7, 0x63, 0x7b, 0x42, 0xb5, 0x39, 0x3e, 0xc0, 0x51, 0xd1, 0x64, 0x17,
	0x4b, 0x2e, 0x89, 0xdd, 0x49, 0xe8, 0x7f, 0x85, 0x77, 0xdb, 0xa1, 0xb3, 0x12, 0x3a, 0x8c, 0x55,
	0xd7, 0x8b, 0x7f, 0x6d, 0x23, 0x7d, 0x65, 0xca, 0x24, 0xf6, 0xb5, 0x6d, 0x53, 0xbc, 0x81, 0xce,
	0xba, 0x25, 0x27, 0xd1, 0x49, 0x36, 0x5c, 0xaa, 0x2a, 0x88, 0xb0, 0x8f, 0xf6, 0xc3, 0x09, 0x5e,
	0x86, 0x85, 0x9f, 0xaf, 0xa0, 0x9b, 0xbd, 0xa1, 0xcf, 0x17, 0xf6, 0x56, 0xe1, 0x9d, 0x97, 0x5f,
	0x79, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x61, 0xbc, 0xe0, 0x8b, 0x2a, 0x01, 0x00, 0x00,
}
